// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuT1CDm5kXpIjZlLWiT-FtSzvXSXjECds',
    appId: '1:1092859709585:web:d425c2f8277fd00efc1730',
    messagingSenderId: '1092859709585',
    projectId: 'umkm-kalibaru-manis',
    authDomain: 'umkm-kalibaru-manis.firebaseapp.com',
    storageBucket: 'umkm-kalibaru-manis.firebasestorage.app',
    measurementId: 'G-NL4Q8KW9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7EIods7sNWAJUxMNbF4nYynJEF37puqM',
    appId: '1:1092859709585:android:79b361f4396b937afc1730',
    messagingSenderId: '1092859709585',
    projectId: 'umkm-kalibaru-manis',
    storageBucket: 'umkm-kalibaru-manis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZWzY0n9a_Fmmu23kRD5HFeAhyGLunAI',
    appId: '1:1092859709585:ios:da4373c066d5c87efc1730',
    messagingSenderId: '1092859709585',
    projectId: 'umkm-kalibaru-manis',
    storageBucket: 'umkm-kalibaru-manis.firebasestorage.app',
    iosBundleId: 'com.example.pencatatanKeuangan',
  );
}
